POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Douglas Dias Leal",
  "email": "douglas_san@hotmail.com"
}

###

GET http://localhost:3333/invites/douglas123

###

GET http://localhost:3333/subscribers/douglas123/ranking/clicks

###